spring:
  application:
    name: servicePvd
server:
  port: 8003
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7000/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"


