spring:
  application:
    name: eurekaServer
  profiles: server3

server:
  port: 7003

eureka:
  instance:
    hostname: server3
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://server1:7001/eureka/,http://server2:7002/eureka/,http://server3:7003/eureka/
